require:
- rubocop-rspec

AllCops:
  Exclude:
  - 'vendor/**/*'
  - 'tmp/**/*'
  - 'bin/*'

  TargetRubyVersion: 2.6

Metrics/AbcSize:
  Max: 30

Metrics/LineLength:
  Max: 120
  IgnoredPatterns: ['\A#']

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'db/seeds.rb'
    - 'app/queries/concerns/paginable.rb'

Style/AsciiComments:
  Enabled: false

Metrics/BlockLength:
  Exclude:
  - 'spec/rails_helper.rb'
  - 'spec/**/*'
  - 'config/routes.rb'
  - 'lib/tasks/*'
  - 'config/environments/*'

Style/ExpandPathArguments:
  Exclude:
  - 'spec/rails_helper.rb'

RSpec/ContextWording:
  Enabled: false

Style/RescueStandardError:
  Exclude:
  - 'app/interactors/**/*'

RSpec/MessageChain:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Documentation:
  Enabled: false
