version: '3'
services:
  store-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/var/www/store-api
    environment:
      - DATABASE_URL=postgresql://store_dev:store_dev@postgres:5432/store_dev
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
    command: puma

  postgres:
    image: postgres:11
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=store_dev
      - POSTGRES_USER=store_dev
      - POSTGRES_PASSWORD=store_dev
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
     - store-pg-data:/var/lib/postgresql/data/pgdata

  redis:
    image: redis:5
    ports:
      - "7379:6379"
    command: redis-server --save "" --appendonly no

volumes:
  store-pg-data:
