version: '3'
services:
  store-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/var/www/store-api
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://store_dev:store_dev@postgres:5432/store_dev
      - SESSION_REDIS_HOST=redis
      - SESSION_REDIS_PORT=6379
      - SESSION_PREFIX='session:'
      - SESSION_REDIS_EXPIRE=86660
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
    command: bundle exec rails server -b 0.0.0.0

  postgres:
    image: postgres:15.4
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=store_dev
      - POSTGRES_USER=store_dev
      - POSTGRES_PASSWORD=store_dev
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
     - store-pg-data:/var/lib/postgresql/data/pgdata

  redis:
    image: redis:7.2.0
    ports:
      - "7379:6379"
    command: redis-server --save "" --appendonly no

volumes:
  store-pg-data:
