default: &default
  adapter: postgresql
  encoding: unicode
  reconnect: true
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("DATABASE_PORT") { '5432' } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { 'store_dev' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { 'store_dev' } %>
  url: <%= ENV['PG_URL'] %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { 'store_dev' } %>

test:
  <<: *default
  database: store_test

staging:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>

production:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>
