development: &default
  host: <%= ENV.fetch("SESSION_REDIS_HOST") %>
  port: <%= ENV.fetch("SESSION_REDIS_PORT") %>
  db: <%= ENV.fetch("SESSION_REDIS_DB") { 2 } %>
  expire_after: <%= ENV.fetch("SESSION_REDIS_EXPIRE") { 36400 } %>
  prefix: <%= "\"#{ENV.fetch("SESSION_PREFIX") { 'session:' }}\""  %>
staging:
  <<: *default
production:
  <<: *default
test:
  <<: *default
  db: <%= ENV.fetch("SESSION_REDIS_DB") { 11 } %>
